import { useFormikContext } from "formik";
import { useEffect, useRef } from "react";
import { parseSkuQuantity } from "../../Utils/CustomFunctions/ParseSkuQuantity";

const VariationSkuAssistant = () => {
    const { values, setFieldValue } = useFormikContext();
    const prevBaseSku = useRef(values.sku);
    const lastAutoGeneratedSkus = useRef({}); // Maps index -> last suggested SKU

    useEffect(() => {
        // Only run if we have a base SKU to work with
        if (!values.sku) return;

        const variations = values.variations || [];
        const optionsList = values.variation_options || [];
        
        let hasUpdates = false;
        const newVariations = variations.map((variation, index) => {
            const options = optionsList[index] || [];
            
            if (!options || options.length === 0) return variation;

            const optionSuffixes = options.map(opt => {
                const val = String(opt.value || "");
                return parseSkuQuantity(val);
            }).filter(Boolean);

            if (optionSuffixes.length === 0) return variation;

            const suggestedSku = `${values.sku}-${optionSuffixes.join('-')}`.replace(/-+/g, '-');

            const currentSku = variation.sku || "";
            const currentBarcode = variation.barcode || "";
            const lastGenerated = lastAutoGeneratedSkus.current[index] || "";

            const shouldUpdate = (!currentSku || currentSku === lastGenerated) || (!currentBarcode || currentBarcode === lastGenerated);

            if (shouldUpdate && (currentSku !== suggestedSku || currentBarcode !== suggestedSku)) {
                hasUpdates = true;
                lastAutoGeneratedSkus.current[index] = suggestedSku;
                return { 
                    ...variation, 
                    sku: (!currentSku || currentSku === lastGenerated) ? suggestedSku : currentSku,
                    barcode: (!currentBarcode || currentBarcode === lastGenerated) ? suggestedSku : currentBarcode
                };
            }

            return variation;
        });

        if (hasUpdates) {
            // We use a slight timeout or check to prevent infinite loops 
            // if Formik updates trigger this effect too aggressively
            setFieldValue("variations", newVariations);
        }

        prevBaseSku.current = values.sku;
    }, [values.sku, values.variation_options, values.variations?.length]);

    return null;
};

export default VariationSkuAssistant;
